debug: false

server:
  port: 8000

spring:
  application:
    name: taskman
    description: Manage daily tasks and increase production
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true