## Basic
spring:
  application:
    name: taskman
    description: An app to manage daily taskEntity and increase production!
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

## Postgres
#spring.datasource.url = ???
#spring.datasource.username = ???
#spring.datasource.password = ???
#spring.datasource.port = ???
#spring.jpa.hibernate.ddl-auto = ???

## H2

## Active Profile
#spring.profiles.active = dev

## JWT_SECRET

## SONAR

